config/urls.py
from django.conf import settings
from django.contrib.auth import views as django_auth_views
from django.urls import include, path
from linkysets.users import views as auth_views

auth_urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login",),
    path("logout/", django_auth_views.LogoutView.as_view(), name="logout"),
    path("register/", auth_views.RegisterView.as_view(), name="register"),
]

urlpatterns = auth_urlpatterns + [
    path("", include("linkysets.entries.urls", namespace="entries")),
    path("replies/", include("linkysets.replies.urls", namespace="replies")),
    path("users/", include("linkysets.users.urls", namespace="users")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls))  # noqa: DJ05
    ]

linkysets/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("detail/<str:pk>/", views.EntrySetDetailView.as_view(), name="detail"),
    path("create/", views.create_entryset_view, name="create"),
    path("edit/<str:pk>/", views.edit_entryset_view, name="edit"),
    path("delete/<str:pk>/", views.EntrySetDeleteView.as_view(), name="delete"),
    path("repost/<str:pk>/", views.repost_entry_view, name="repost"),
]

linkysets/replies/urls.py
from django.urls import path

from . import views

app_name = "replies"

urlpatterns = [
    path("post/", views.PostReplyView.as_view(), name="post"),
]

linkysets/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

linkysets/common/forms.py
from typing import Any, Generic, Optional, TypeVar, Union

from django.db.models import Model
from django.utils.crypto import get_random_string

I = TypeVar("I", bound=Model)  # noqa: E741

_MISSING = object()


class AssignUserMixin(Generic[I]):
    instance: I
    user_field_name: str = "user"

    def __init__(self, *args, user: Optional[Any] = _MISSING, **kwargs):
        super().__init__(*args, **kwargs)  # type: ignore
        self.user = user

    def save(self, commit: bool = True) -> I:  # noqa: E741
        if not hasattr(self.instance, self.user_field_name):
            raise ValueError(
                f'"{type(self.instance).__name__}" '
                f'does not have user field with a name "{self.user_field_name}".'
            )

        if self.user is not _MISSING:
            setattr(self.instance, self.user_field_name, self.user)

        return super().save(commit)  # type: ignore


class UniqueAutoIdMixin:
    _auto_id: Union[bool, str]

    @property
    def auto_id(self) -> Union[bool, str]:
        if isinstance(self._auto_id, bool):
            return self._auto_id

        unique_suffix = get_random_string(6)
        return f"{self._auto_id}_{unique_suffix}"

    @auto_id.setter
    def auto_id(self, auto_id: Union[bool, str]) -> None:
        self._auto_id = auto_id

linkysets/replies/forms.py
from __future__ import annotations

from typing import TYPE_CHECKING, Optional

from django import forms

from linkysets.common.forms import AssignUserMixin

from .models import Reply

if TYPE_CHECKING:
    from linkysets.entries.models import EntrySet


class ReplyForm(AssignUserMixin[Reply], forms.ModelForm):
    user_field_name = "author"

    class Meta:
        model = Reply
        fields = ["parent", "text"]
        widgets = {
            "parent": forms.HiddenInput(),
        }

    def __init__(self, *args, entryset: Optional[EntrySet] = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.entryset = entryset

    def save(self, commit: bool = True) -> Reply:
        if self.entryset is None:
            raise ValueError("Entryset is required.")

        self.instance.entryset = self.entryset
        return super().save(commit=commit)

linkysets/common/views.py
from __future__ import annotations

from typing import (
    ClassVar,
    Dict,
    Iterable,
    NamedTuple,
    Optional,
    Sequence,
    Tuple,
    Type,
    Union,
)

from django.apps import apps
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Model
from django.http import Http404, HttpRequest, HttpResponse


class QsObjectMeta(NamedTuple):
    name: str
    model: Union[str, Type[Model]]
    is_required: bool = True
    filter_field: str = "pk"


QsObjectTuple = Tuple[Optional[Model], QsObjectMeta]
FinalQsObjectTuple = Tuple[Model, QsObjectMeta]


class QuerystringObjectsMixin:
    request: HttpRequest

    qs_objects_meta: ClassVar[Sequence[QsObjectMeta]]
    qs_objects: Dict[str, FinalQsObjectTuple]

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        qs_objects = list(self._get_querystring_objects())
        for obj, meta in qs_objects:
            if obj is not None:
                continue

            try:
                return self.get_no_qs_object_response(meta)
            except NotImplementedError:
                name, model, *_ = meta
                model_string = model if isinstance(model, str) else model.__name__
                raise Http404(
                    f'Unable to get required "{model_string}" object '
                    f'from query string parameter "{name}".'
                )

        self.qs_objects = {
            meta.name: (obj, meta) for obj, meta in qs_objects  # type: ignore
        }
        return super().dispatch(request, *args, **kwargs)  # type: ignore

    def get_no_qs_object_response(self, meta: QsObjectMeta) -> HttpResponse:
        raise NotImplementedError(
            '"get_no_qs_object_response" should be implemented in a view class.'
        )

    def _get_querystring_objects(self) -> Iterable[QsObjectTuple]:
        querydict = self.request.GET
        for meta in self.qs_objects_meta:
            name, model_or_string, is_required, filter_field = meta

            if isinstance(model_or_string, str):
                model: Type[Model] = apps.get_model(model_or_string)
            else:
                model = model_or_string

            param_value = querydict.get(name)
            if not param_value and is_required:
                raise ValueError(
                    f'Querystring parameter "{name}" is required. Got value: {param_value}'
                )

            if not param_value and not is_required:
                continue

            try:
                obj = model._default_manager.get(**{filter_field: param_value})
            except ObjectDoesNotExist:
                yield None, meta
            else:
                yield obj, meta


class ObjectPermissionRequiredMixin(PermissionRequiredMixin):
    request: HttpRequest

    def has_permission(self) -> bool:
        perms = self.get_permission_required()
        obj = getattr(self, "object", self.get_object())  # type: ignore
        return self.request.user.has_perms(perms, obj)

linkysets/entries/views.py
# flake8: noqa: W503
from __future__ import annotations

import logging
from typing import Any, Dict

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_POST
from django.views.generic import DeleteView, DetailView, ListView

from linkysets.common.typing import SupportsStr
from linkysets.common.views import ObjectPermissionRequiredMixin

from .forms import EntryFormset, EntrySetForm, SearchForm
from .managers import EntrySetQuerySet
from .mixins import EntrySetPermissionMixin, PageTitleMixin
from .models import Entry, EntrySet
from .utils import join_page_title

logger = logging.getLogger(__name__)


class HomeView(PageTitleMixin, ListView):
    queryset = EntrySet.objects.all()
    template_name = "entries/home.html"
    ordering = "created"
    paginate_by = 10

    def get_full_title(self) -> SupportsStr:
        return settings.PAGE_TITLE_EXTENSION


class SearchView(PageTitleMixin, ListView):
    template_name = "entries/search.html"
    paginate_by = 10
    page_title = _("Search")

    form: SearchForm

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.form = SearchForm(request.GET or None, initial=request.GET)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = self.form
        return context

    def get_queryset(self) -> EntrySetQuerySet:
        if not self.form.is_valid():
            return EntrySet.objects.none()

        term = self.form.cleaned_data.get("term")
        qs = EntrySet.objects.all()
        qs = qs.filter(
            Q(name__unaccent__lower__trigram_similar=term)
            | Q(author__username__icontains=term)
            | Q(entries__label__unaccent__lower__trigram_similar=term)
            | Q(entries__url__icontains=term)
        )
        qs = qs.order_by("created").distinct()
        return qs


def create_entryset_view(request: HttpRequest) -> HttpResponse:
    user = request.user if request.user.is_authenticated else None
    form = EntrySetForm(request.POST or None, user=user)
    formset = EntryFormset(request.POST or None)

    if request.method == "POST":
        if form.is_valid() and formset.is_valid():  # type: ignore
            with transaction.atomic():
                entryset = form.save()
                formset.instance = entryset
                saved_entries = formset.save()
                entryset.entries.set(saved_entries)

            logger.debug(
                'Entryset has been created: "%s". Entries: %s',
                entryset,
                ", ".join(str(entry) for entry in entryset.entries.all()),
            )
            return redirect(entryset)

    context = {
        "form": form,
        "formset": formset,
        "hero_title": _("Create set"),
        "submit_text": _("Create"),
        "page_title": join_page_title(_("Create set")),
    }
    return render(request, "entries/entryset_form.html", context)


@login_required
def edit_entryset_view(request: HttpRequest, pk: Any) -> HttpResponse:
    entryset = get_object_or_404(EntrySet, pk=pk)
    if not request.user.has_perm("entries.change_entryset", entryset):
        return redirect(settings.LOGIN_URL)

    form = EntrySetForm(request.POST or None, instance=entryset)
    formset = EntryFormset(request.POST or None, instance=entryset)

    if request.method == "POST":
        updated = False
        if form.has_changed() and form.is_valid():
            entryset = form.save()
            updated = True

        if formset.is_valid():  # type: ignore
            saved_entries = formset.save(commit=False)

            entryset.entries.remove(*formset.deleted_objects)
            for entry in formset.deleted_objects:
                entry.delete()

            for entry in saved_entries:
                entry.save()
            entryset.entries.add(*saved_entries)

            logger.debug(
                "Entry formset saved entries: %s. Deleted entries: %s",
                saved_entries,
                formset.deleted_objects,
            )
            updated = True

        if updated:
            msg = _('"%(entryset)s" set has been successfully updated.')
            messages.success(request, msg % {"entryset": entryset})
            return redirect("entries:home")

    context = {
        "form": form,
        "formset": formset,
        "hero_title": _("Edit set"),
        "submit_text": _("Confirm"),
        "page_title": join_page_title(_("Edit set")),
    }
    return render(request, "entries/entryset_form.html", context)


class EntrySetDeleteView(PageTitleMixin, ObjectPermissionRequiredMixin, DeleteView):
    model = EntrySet
    template_name = "entries/entryset_delete.html"
    success_url = reverse_lazy("entries:home")
    permission_required = ["entries.delete_entryset"]
    page_title = _("Delete set")
    success_message = _('"%(entryset)s" set has been succesfully deleted.')

    def delete(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        response = super().delete(request, *args, **kwargs)
        messages.success(
            request, self.success_message % {"entryset": self.object}  # type: ignore
        )
        return response


class EntrySetDetailView(EntrySetPermissionMixin, PageTitleMixin, DetailView):
    queryset = EntrySet.objects.prefetch_replies()
    template_name = "entries/entryset_detail.html"
    title_object_name = "object"


@require_POST
@login_required
def repost_entry_view(request: HttpRequest, pk: Any) -> HttpResponse:
    if Entry.objects.filter(pk=pk).exists():
        user = request.user if request.user.is_authenticated else None
        with transaction.atomic():
            entryset = EntrySet.objects.create(author=user)
            entryset.entries.add(pk)
    else:
        raise Http404(f"No {Entry._meta.object_name} matches the given query.")

    return redirect("entries:edit", pk=entryset.pk)

linkysets/replies/views.py
from typing import Any, Dict, Optional, cast

from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView

from linkysets.common.views import QsObjectMeta, QuerystringObjectsMixin
from linkysets.entries.mixins import PageTitleMixin
from linkysets.entries.models import EntrySet

from .forms import ReplyForm
from .models import Reply


class PostReplyView(PageTitleMixin, QuerystringObjectsMixin, CreateView):
    model = Reply
    form_class = ReplyForm
    template_name = "replies/post_reply.html"
    page_title = _("Post reply")

    qs_objects_meta = [
        QsObjectMeta("entryset", EntrySet),
        QsObjectMeta("reply", Reply, is_required=False),
    ]

    def get_context_data(self, **kwargs) -> Dict[Any, Any]:
        context = super().get_context_data(**kwargs)
        return {
            **context,
            "entryset": self.entryset,
            "parent_reply": self.parent_reply,
        }

    def get_form_kwargs(self) -> Dict[Any, Any]:
        kwargs = super().get_form_kwargs()
        user = self.request.user if self.request.user.is_authenticated else None
        return {
            **kwargs,
            "user": user,
            "entryset": self.entryset,
        }

    def get_initial(self) -> Dict[Any, Any]:
        initial_data = super().get_initial()
        return {
            **initial_data,
            "parent": self.parent_reply,
        }

    def get_success_url(self) -> str:
        return self.entryset.get_absolute_url()

    @property
    def entryset(self) -> EntrySet:
        entryset = self.qs_objects["entryset"]
        return cast(EntrySet, entryset[0])

    @property
    def parent_reply(self) -> Optional[Reply]:
        reply = self.qs_objects.get("reply")
        if reply is None:
            return reply
        return cast(Reply, reply[0])

linkysets/users/views.py
from __future__ import annotations

from typing import Any, Dict

from django.contrib.auth.views import LoginView as DjangoLoginView
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, DetailView

from linkysets.entries.mixins import PageTitleMixin

from .forms import AuthenticationForm, UserCreationForm
from .models import User


class LoginView(PageTitleMixin, DjangoLoginView):
    authentication_form = AuthenticationForm
    page_title = _("Login")

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["hero_title"] = self.page_title
        return context


class RegisterView(PageTitleMixin, CreateView):
    form_class = UserCreationForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("entries:home")
    page_title = _("Register")

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["hero_title"] = self.page_title
        return context


class UserDetailView(PageTitleMixin, DetailView):
    template_name = "users/user_detail.html"
    queryset = User.objects.num_entrysets().num_replies()
    slug_field = "username"
    slug_url_kwarg = "username"
    title_object_name = "object"

    entrysets_per_page: int = 5
    replies_per_page: int = 5

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        entrysets_page_num = self.request.GET.get("sets_page", 1)
        entrysets_qs = self.object.entryset_set.order_by("-created")  # type: ignore
        context["entrysets_page"] = Paginator(entrysets_qs, self.entrysets_per_page,).page(
            entrysets_page_num
        )

        replies_page_num = self.request.GET.get("replies_page", 1)
        replies_qs = self.object.reply_set.select_related(  # type: ignore
            "parent", "entryset"
        ).order_by("-created")
        context["replies_page"] = Paginator(replies_qs, self.replies_per_page,).page(
            replies_page_num
        )

        return context

linkysets/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
        {{ page_title }}
      {% endblock title %}
    </title>

    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'favicon/apple-touch-icon.png' %}"
    >
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'favicon/favicon-32x32.png' %}"
    >
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'favicon/favicon-16x16.png' %}"
    >

    {% block css %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock css %}
  {% endblock head %}
</head>
<body>
  {% include "header.html" %}

  <main>
    {% block content %}
      {% if messages %}
        <div class="container">
          <ul class="list-unstyled my-3">
            {% for message in messages %}
              <li
                class="alert {% if message.tags %}{{ message.tags }}{% endif %}"
                role="alert"
              >
                {{ message }}
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
    {% endblock content %}
  </main>

  {% include "footer.html" %}

  {% block js %}
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
  {% endblock js %}
</body>
</html>

linkysets/templates/footer.html
{% load i18n %}

<footer class="jumbotron jumbotron-fluid m-0 py-4">
  <div class="container">
    <div class="row mb-3">
      <div class="col text-center">
        <a
          href="{% url 'entries:create' %}"
          class="btn btn-outline-primary btn-lg font-weight-bold"
        >
          {% trans "Create unique set" %}
        </a>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-12 col-sm-6 col-lg-3 mb-2 mb-sm-0">
        <ol class="list-group list-group-flush rounded">
          <li class="list-group-item list-group-item-dark font-dark font-weight-bold">
            {% trans "Recent sets" %}
          </li>

          {% for entryset in recent_entrysets %}
            <li class="list-group-item">
              <a
                href="{{ entryset.get_absolute_url }}"
                class="font-weight-bold text-decoration-none"
              >
                {{ entryset }}
              </a>

              {% with entryset.get_author as author %}
                <a
                  href="{{ author.get_absolute_url }}"
                  class="text-muted"
                >
                  <small>
                    {{ author.username }}
                  </small>
                </a>
              {% endwith %}
            </li>
          {% empty %}
            <li class="list-group-item text-center">
              <i>
                {% trans "No recent sets yet." %}
              </i>
            </li>
          {% endfor %}
        </ol>
      </div>

      <div class="col-12 col-sm-6 col-lg-3">
        <ol class="list-group list-group-flush rounded">
          <li class="list-group-item list-group-item-dark font-dark font-weight-bold">
            {% trans "Top authors" %}
          </li>

          {% for author in top_authors %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <a
                href="{{ author.get_absolute_url }}"
                class="font-weight-bold text-decoration-none"
              >
                {{ author.username }}
              </a>

              <span class="badge badge-dark badge-pill">
                {{ author.num_sets }}
              </span>
            </li>
          {% empty %}
            <li class="list-group-item text-center">
              <i>
                {% trans "No authors yet." %}
              </i>
            </li>
          {% endfor %}
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col d-flex justify-content-center">
        {% now "Y" as year %}
        {% blocktrans with year=year host=request.get_host trimmed %}
          &#169; {{ year }} {{ host }}. All Rights Reserved.
        {% endblocktrans %}
      </div>
    </div>
  </div>
</footer>

linkysets/templates/header.html
{% load i18n %}

<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark py-3">
    <a href="{% url 'entries:home' %}" class="navbar-brand font-weight-bold border-bottom">
      🗃 Linkysets
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <form
        action="{% url 'entries:search' %}"
        method="get"
        class="form-inline ml-2 my-3 my-md-0"
      >
        <div class="input-group">
          {% with search_form.term as field %}
            <input
              type="search"
              name="{{ field.html_name }}"
              placeholder="{{ field.help_text }}"
              id="{{ field.id_for_label }}"
              {% if field.field.max_length %}
                max-length="{{ field.field.max_length }}"
              {% endif %}
              class="form-control"
            >
          {% endwith %}

          <div class="input-group-append">
            <button type="submit" class="btn btn-outline-primary">
              {% trans "Search" %}
            </button>
          </div>
        </div>
      </form>

      <div class="ml-2 ml-md-auto">
        {% if user.is_authenticated %}
          <small class="navbar-text">
            {% trans "You are logged in as" %}
          </small>

          <a href="{{ user.get_absolute_url }}" class="text-decoration-none mr-2">
            {{ user.username }}
          </a>

          <a href="{% url 'logout' %}" class="btn btn-outline-danger">
            {% trans "Logout" %}
          </a>
        {% else %}
          <form
            action="{% url 'login' %}"
            method="post"
            class="text-light d-block d-md-none"
          >
            {% csrf_token %}

            {% for field in login_form.hidden_fields %}
              {{ field }}
            {% endfor %}

            <div class="form-row">
              {% for field in login_form.visible_fields %}
                <div class="form-group col-12 col-sm-6 my-1">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                  </label>

                  <input
                    type="{{ field.field.widget.input_type }}"
                    name="{{ field.html_name }}"
                    placeholder="{{ field.label }}"
                    id="{{ field.id_for_label }}"
                    autocomplete="current-password"
                    class="form-control"
                  >
                </div>

                {% if not forloop.last %}
                  <div class="w-100"></div>
                {% endif %}
              {% endfor %}
            </div>

            <div class="mt-2">
              <button type="submit" class="btn btn-outline-primary">
                {% trans "Login" %}
              </button>

              <a href="{% url 'register' %}" class="btn btn-outline-success">
                {% trans "Register" %}
              </a>
            </div>
          </form>

          <div class="d-none d-md-flex">
            <div class="dropdown mr-2">
              <button
                class="btn btn-outline-primary dropdown-toggle"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                {% trans "Login" %}
              </button>

              <div class="dropdown-menu dropdown-menu-right" style="width: 13rem;">
                <form action="{% url 'login' %}" method="post" class="px-4 py-2">
                  {% csrf_token %}
                  {% include "users/includes/login_form.html" with form=login_form %}

                  <button type="submit" class="btn btn-primary">
                    {% trans "Login" %}
                  </button>
                </form>
              </div>
            </div>

            <a href="{% url 'register' %}" class="btn btn-outline-success">
              {% trans "Register" %}
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

linkysets/templates/hero.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid my-4">
    <div class="row rows-col-1 justify-content-center">
      <div class="col-md-8 col-xl-6">
        {{ block.super }}

        {% if hero_title %}
          <h1 class="display-4 mb-3 text-center">
            {{ hero_title }}
          </h1>
        {% endif %}

        {% block hero_content %}{% endblock hero_content %}
      </div>
    </div>
  </div>
{% endblock content %}

linkysets/templates/pagination.html
{% load common_tags %}

<nav aria-label="Pagination">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      {% transform_query prefix=prefix page=page_obj.previous_page_number as previous_page_query %}

      <li class="page-item">
        <a href="?{{ previous_page_query }}" class="page-link">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>

      <li class="page-item {% if page_obj.number == 1 %}disabled{% endif %}">
        <a href="?{% transform_query prefix=prefix page=1 %}" class="page-link">
          1
        </a>
      </li>

      {% if page_obj.previous_page_number != 1 %}
        <li class="page-item">
          <a href="?{{ previous_page_query }}" class="page-link">
            {{ page_obj.previous_page_number }}
          </a>
        </li>
      {% endif %}
    {% endif %}

    <li class="page-item active">
      <a href="#" class="page-link">
        {{ page_obj.number }}
      </a>
    </li>

    {% if page_obj.has_next %}
      {% transform_query prefix=prefix page=page_obj.next_page_number as next_page_query %}

      {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
        <li class="page-item">
          <a href="?{{ next_page_query }}" class="page-link">
            {{ page_obj.next_page_number }}
          </a>
        </li>
      {% endif %}

      <li class="page-item">
        <a href="?{% transform_query prefix=prefix page=page_obj.paginator.num_pages %}" class="page-link">
          {{ page_obj.paginator.num_pages }}
        </a>
      </li>

      <li class="page-item">
        <a href="?{{ next_page_query }}" class="page-link">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>