config/urls.py
from django.conf import settings
from django.contrib.auth import views as django_auth_views
from django.urls import include, path
from linkysets.users import views as auth_views

auth_urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login",),
    path("logout/", django_auth_views.LogoutView.as_view(), name="logout"),
    path("register/", auth_views.RegisterView.as_view(), name="register"),
]

urlpatterns = auth_urlpatterns + [
    path("", include("linkysets.entries.urls", namespace="entries")),
    path("replies/", include("linkysets.replies.urls", namespace="replies")),
    path("users/", include("linkysets.users.urls", namespace="users")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls))  # noqa: DJ05
    ]

linkysets/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("detail/<str:pk>/", views.EntrySetDetailView.as_view(), name="detail"),
    path("create/", views.create_entryset_view, name="create"),
    path("edit/<str:pk>/", views.edit_entryset_view, name="edit"),
    path("delete/<str:pk>/", views.EntrySetDeleteView.as_view(), name="delete"),
    path("repost/<str:pk>/", views.repost_entry_view, name="repost"),
]

linkysets/replies/urls.py
from django.urls import path

from . import views

app_name = "replies"

urlpatterns = [
    path("post/", views.PostReplyView.as_view(), name="post"),
]

linkysets/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

linkysets/entries/models.py
from __future__ import annotations

import logging
from collections import OrderedDict
from typing import cast

from django.core.exceptions import ValidationError
from django.db import models
from django.shortcuts import reverse  # type: ignore
from django.utils.translation import ugettext_lazy as _

from linkysets.common.models import AuthoredModel, TimestampedModel

from . import behavior
from .behavior import EntryTypeBehavior
from .managers import EntrySetManager, EntrySetQuerySet

logger = logging.getLogger(__name__)


class EntrySet(TimestampedModel, AuthoredModel):
    name = models.CharField(
        _("name"), max_length=50, blank=True, help_text=_("Set name (optional).")
    )
    entries = models.ManyToManyField(
        "Entry",
        related_name="sets",
        verbose_name=_("entries"),
        help_text=_("Entries that this set contains."),
    )

    objects = EntrySetManager.from_queryset(EntrySetQuerySet)()

    class Meta:
        verbose_name = _("entry set")
        verbose_name_plural = _("entry sets")

    def __str__(self) -> str:
        if self.name:
            return self.name

        author = self.get_author()
        return _("%(username)s's nameless set") % {"username": author.username}

    def get_absolute_url(self) -> str:
        return reverse("entries:detail", kwargs={"pk": self.pk})

    def clean(self):
        if not self._state.adding and self.entries.count() == 0:  # type: ignore
            raise ValidationError("Entryset cannot have zero entries.", code="no_entries")


class Entry(models.Model):
    class EntryType(models.IntegerChoices):
        URL = 0, _("URL")
        IMAGE = 1, _("Image")
        VIDEO = 2, _("Video")
        YT_VIDEO = 3, _("Youtube video")
        AUDIO = 4, _("Audio")

    _TYPE_BEHAVIOR_DICT = OrderedDict(
        (
            (EntryType.IMAGE, behavior.ImageTypeBehavior),
            (EntryType.VIDEO, behavior.VideoTypeBehavior),
            (EntryType.AUDIO, behavior.AudioBehavior),
            (EntryType.YT_VIDEO, behavior.YtVideoTypeBehavior),
            # URL behavior must be last in the dict,
            # because it always return true for is_my_type test
            (EntryType.URL, behavior.UrlTypeBehavior),
        )
    )

    type = models.PositiveSmallIntegerField(
        _("type"),
        choices=EntryType.choices,
        blank=True,
        default=EntryType.URL,
        help_text=_("Supported entry type."),
    )
    url = models.URLField(
        _("URL"), max_length=400, help_text=_("URL of the resource to share.")
    )
    label = models.CharField(
        _("label"), max_length=100, blank=True, help_text=_("Entry label (optional).")
    )
    origin = models.ForeignKey(
        EntrySet,
        on_delete=models.SET_NULL,
        related_name="original_entries",
        null=True,
        editable=False,
        verbose_name=_("origin"),
        help_text=_("Original entry set of the entry."),
    )

    class Meta:
        verbose_name = _("entry")
        verbose_name_plural = _("entries")

    def __str__(self):
        return self.label or self.url

    def delete(self, *args, **kwargs):
        sets_count = self.sets.count()
        if sets_count != 0:
            logger.debug(
                "Entry \"%s\" hasn't been deleted because it's posted to %d entrysets.",
                self,
                sets_count,
            )
            return

        logger.debug('Entry "%s" (pk=%s) got deleted.', self, self.pk)
        return super().delete(*args, **kwargs)

    def render(self) -> str:
        return self.type_behavior.render()

    def determine_type(self, url: str, mime_type: str, *args, **kwargs) -> EntryType:
        for type_, behavior_cls in self._TYPE_BEHAVIOR_DICT.items():
            if behavior_cls.is_my_type(self, url, mime_type, *args, **kwargs):
                return type_

        return self._meta.get_field("type").default

    @property
    def type_behavior(self) -> EntryTypeBehavior:
        type_ = cast(Entry.EntryType, self.type)
        behavior_cls = self._TYPE_BEHAVIOR_DICT[type_]
        return behavior_cls(self)

linkysets/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm as DjangoAuthenticationForm,
    UserCreationForm as DjangoUserCreationForm,
)

from linkysets.common.forms import UniqueAutoIdMixin


class UserCreationForm(DjangoUserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "password1", "password2"]


class AuthenticationForm(UniqueAutoIdMixin, DjangoAuthenticationForm):  # type: ignore
    """
    Linkysets authentication form
    """

linkysets/common/views.py
from __future__ import annotations

from typing import (
    ClassVar,
    Dict,
    Iterable,
    NamedTuple,
    Optional,
    Sequence,
    Tuple,
    Type,
    Union,
)

from django.apps import apps
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Model
from django.http import Http404, HttpRequest, HttpResponse


class QsObjectMeta(NamedTuple):
    name: str
    model: Union[str, Type[Model]]
    is_required: bool = True
    filter_field: str = "pk"


QsObjectTuple = Tuple[Optional[Model], QsObjectMeta]
FinalQsObjectTuple = Tuple[Model, QsObjectMeta]


class QuerystringObjectsMixin:
    request: HttpRequest

    qs_objects_meta: ClassVar[Sequence[QsObjectMeta]]
    qs_objects: Dict[str, FinalQsObjectTuple]

    def dispatch(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        qs_objects = list(self._get_querystring_objects())
        for obj, meta in qs_objects:
            if obj is not None:
                continue

            try:
                return self.get_no_qs_object_response(meta)
            except NotImplementedError:
                name, model, *_ = meta
                model_string = model if isinstance(model, str) else model.__name__
                raise Http404(
                    f'Unable to get required "{model_string}" object '
                    f'from query string parameter "{name}".'
                )

        self.qs_objects = {
            meta.name: (obj, meta) for obj, meta in qs_objects  # type: ignore
        }
        return super().dispatch(request, *args, **kwargs)  # type: ignore

    def get_no_qs_object_response(self, meta: QsObjectMeta) -> HttpResponse:
        raise NotImplementedError(
            '"get_no_qs_object_response" should be implemented in a view class.'
        )

    def _get_querystring_objects(self) -> Iterable[QsObjectTuple]:
        querydict = self.request.GET
        for meta in self.qs_objects_meta:
            name, model_or_string, is_required, filter_field = meta

            if isinstance(model_or_string, str):
                model: Type[Model] = apps.get_model(model_or_string)
            else:
                model = model_or_string

            param_value = querydict.get(name)
            if not param_value and is_required:
                raise ValueError(
                    f'Querystring parameter "{name}" is required. Got value: {param_value}'
                )

            if not param_value and not is_required:
                continue

            try:
                obj = model._default_manager.get(**{filter_field: param_value})
            except ObjectDoesNotExist:
                yield None, meta
            else:
                yield obj, meta


class ObjectPermissionRequiredMixin(PermissionRequiredMixin):
    request: HttpRequest

    def has_permission(self) -> bool:
        perms = self.get_permission_required()
        obj = getattr(self, "object", self.get_object())  # type: ignore
        return self.request.user.has_perms(perms, obj)

linkysets/entries/views.py
# flake8: noqa: W503
from __future__ import annotations

import logging
from typing import Any, Dict

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_POST
from django.views.generic import DeleteView, DetailView, ListView

from linkysets.common.typing import SupportsStr
from linkysets.common.views import ObjectPermissionRequiredMixin

from .forms import EntryFormset, EntrySetForm, SearchForm
from .managers import EntrySetQuerySet
from .mixins import EntrySetPermissionMixin, PageTitleMixin
from .models import Entry, EntrySet
from .utils import join_page_title

logger = logging.getLogger(__name__)


class HomeView(PageTitleMixin, ListView):
    queryset = EntrySet.objects.all()
    template_name = "entries/home.html"
    ordering = "created"
    paginate_by = 10

    def get_full_title(self) -> SupportsStr:
        return settings.PAGE_TITLE_EXTENSION


class SearchView(PageTitleMixin, ListView):
    template_name = "entries/search.html"
    paginate_by = 10
    page_title = _("Search")

    form: SearchForm

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.form = SearchForm(request.GET or None, initial=request.GET)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = self.form
        return context

    def get_queryset(self) -> EntrySetQuerySet:
        if not self.form.is_valid():
            return EntrySet.objects.none()

        term = self.form.cleaned_data.get("term")
        qs = EntrySet.objects.all()
        qs = qs.filter(
            Q(name__unaccent__lower__trigram_similar=term)
            | Q(author__username__icontains=term)
            | Q(entries__label__unaccent__lower__trigram_similar=term)
            | Q(entries__url__icontains=term)
        )
        qs = qs.order_by("created").distinct()
        return qs


def create_entryset_view(request: HttpRequest) -> HttpResponse:
    user = request.user if request.user.is_authenticated else None
    form = EntrySetForm(request.POST or None, user=user)
    formset = EntryFormset(request.POST or None)

    if request.method == "POST":
        if form.is_valid() and formset.is_valid():  # type: ignore
            with transaction.atomic():
                entryset = form.save()
                formset.instance = entryset
                saved_entries = formset.save()
                entryset.entries.set(saved_entries)

            logger.debug(
                'Entryset has been created: "%s". Entries: %s',
                entryset,
                ", ".join(str(entry) for entry in entryset.entries.all()),
            )
            return redirect(entryset)

    context = {
        "form": form,
        "formset": formset,
        "hero_title": _("Create set"),
        "submit_text": _("Create"),
        "page_title": join_page_title(_("Create set")),
    }
    return render(request, "entries/entryset_form.html", context)


@login_required
def edit_entryset_view(request: HttpRequest, pk: Any) -> HttpResponse:
    entryset = get_object_or_404(EntrySet, pk=pk)
    if not request.user.has_perm("entries.change_entryset", entryset):
        return redirect(settings.LOGIN_URL)

    form = EntrySetForm(request.POST or None, instance=entryset)
    formset = EntryFormset(request.POST or None, instance=entryset)

    if request.method == "POST":
        updated = False
        if form.has_changed() and form.is_valid():
            entryset = form.save()
            updated = True

        if formset.is_valid():  # type: ignore
            saved_entries = formset.save(commit=False)

            entryset.entries.remove(*formset.deleted_objects)
            for entry in formset.deleted_objects:
                entry.delete()

            for entry in saved_entries:
                entry.save()
            entryset.entries.add(*saved_entries)

            logger.debug(
                "Entry formset saved entries: %s. Deleted entries: %s",
                saved_entries,
                formset.deleted_objects,
            )
            updated = True

        if updated:
            msg = _('"%(entryset)s" set has been successfully updated.')
            messages.success(request, msg % {"entryset": entryset})
            return redirect("entries:home")

    context = {
        "form": form,
        "formset": formset,
        "hero_title": _("Edit set"),
        "submit_text": _("Confirm"),
        "page_title": join_page_title(_("Edit set")),
    }
    return render(request, "entries/entryset_form.html", context)


class EntrySetDeleteView(PageTitleMixin, ObjectPermissionRequiredMixin, DeleteView):
    model = EntrySet
    template_name = "entries/entryset_delete.html"
    success_url = reverse_lazy("entries:home")
    permission_required = ["entries.delete_entryset"]
    page_title = _("Delete set")
    success_message = _('"%(entryset)s" set has been succesfully deleted.')

    def delete(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        response = super().delete(request, *args, **kwargs)
        messages.success(
            request, self.success_message % {"entryset": self.object}  # type: ignore
        )
        return response


class EntrySetDetailView(EntrySetPermissionMixin, PageTitleMixin, DetailView):
    queryset = EntrySet.objects.prefetch_replies()
    template_name = "entries/entryset_detail.html"
    title_object_name = "object"


@require_POST
@login_required
def repost_entry_view(request: HttpRequest, pk: Any) -> HttpResponse:
    if Entry.objects.filter(pk=pk).exists():
        user = request.user if request.user.is_authenticated else None
        with transaction.atomic():
            entryset = EntrySet.objects.create(author=user)
            entryset.entries.add(pk)
    else:
        raise Http404(f"No {Entry._meta.object_name} matches the given query.")

    return redirect("entries:edit", pk=entryset.pk)

linkysets/replies/views.py
from typing import Any, Dict, Optional, cast

from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView

from linkysets.common.views import QsObjectMeta, QuerystringObjectsMixin
from linkysets.entries.mixins import PageTitleMixin
from linkysets.entries.models import EntrySet

from .forms import ReplyForm
from .models import Reply


class PostReplyView(PageTitleMixin, QuerystringObjectsMixin, CreateView):
    model = Reply
    form_class = ReplyForm
    template_name = "replies/post_reply.html"
    page_title = _("Post reply")

    qs_objects_meta = [
        QsObjectMeta("entryset", EntrySet),
        QsObjectMeta("reply", Reply, is_required=False),
    ]

    def get_context_data(self, **kwargs) -> Dict[Any, Any]:
        context = super().get_context_data(**kwargs)
        return {
            **context,
            "entryset": self.entryset,
            "parent_reply": self.parent_reply,
        }

    def get_form_kwargs(self) -> Dict[Any, Any]:
        kwargs = super().get_form_kwargs()
        user = self.request.user if self.request.user.is_authenticated else None
        return {
            **kwargs,
            "user": user,
            "entryset": self.entryset,
        }

    def get_initial(self) -> Dict[Any, Any]:
        initial_data = super().get_initial()
        return {
            **initial_data,
            "parent": self.parent_reply,
        }

    def get_success_url(self) -> str:
        return self.entryset.get_absolute_url()

    @property
    def entryset(self) -> EntrySet:
        entryset = self.qs_objects["entryset"]
        return cast(EntrySet, entryset[0])

    @property
    def parent_reply(self) -> Optional[Reply]:
        reply = self.qs_objects.get("reply")
        if reply is None:
            return reply
        return cast(Reply, reply[0])

linkysets/templates/entries/entryset_delete.html
{% extends 'hero.html' %}
{% load i18n %}

{% block hero_content %}
  <h1 class="display-4 mb-4 text-center">
    {% blocktrans with entryset_title=entryset|stringformat:"s" entryset_url=entryset.get_absolute_url trimmed %}
      You're deleting the
      <a href="{{ entryset_url }}" target="_blank" class="text-decoration-none">
        {{ entryset_title }}
      </a>
      set
    {% endblocktrans %}
  </h1>

  <div class="row row-cols-1">
    <div class="col text-center">
      <p class="lead">
        {% trans "Are you sure you want to delete the set?" %}
      </p>
    </div>

    <div class="col d-flex justify-content-center">
      <a href="{{ entryset.get_absolute_url }}" class="btn btn-light btn-lg mr-2">
        {% trans "Cancel" %}
      </a>

      <form action="{% url 'entries:delete' pk=entryset.pk %}" method="post" novalidate>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-lg">
          {% trans "Delete" %}
        </button>
      </form>
    </div>
  </div>
{% endblock hero_content %}

linkysets/templates/entries/entryset_detail.html
{% extends 'base.html' %}
{% load i18n humanize %}

{% block content %}
  <div class="jumbotron jumbotron-fluid mb-0 bg-dark text-light">
    <div class="container">
      <h1 class="display-3 pb-1 font-weight-bold text-center border-bottom">
        {{ entryset }}
      </h1>

      <div class="row row-cols-1">
        <div class="col d-flex justify-content-center">
          <p class="lead mb-0">
            {% with entryset.get_author as author %}
              {% blocktrans with author_name=author.username author_url=author.get_absolute_url creation_date=entryset.created|date:"SHORT_DATETIME_FORMAT" trimmed %}
                by
                <a href="{{ author_url }}" class="text-decoration-none">
                  {{ author_name }}
                </a>
                at
                {{ creation_date }}
              {% endblocktrans %}
            {% endwith %}
          </p>
        </div>

        <div class="col d-flex justify-content-center">
          <p class="lead mb-0 mr-3">
            {% blocktrans with humanized_num_entries=entryset.num_entries|apnumber count num_entries=entryset.num_entries trimmed %}
              {{ humanized_num_entries }} entry
              {% plural %}
              {{ humanized_num_entries }} entries
            {% endblocktrans %}
          </p>

          <p class="lead mb-0">
            {% blocktrans with humanized_num_replies=entryset.num_replies|apnumber count num_replies=entryset.num_replies trimmed %}
              {{ humanized_num_replies }} reply
              {% plural %}
              {{ humanized_num_replies }} replies
            {% endblocktrans %}
          </p>
        </div>
      </div>
    </div>
  </div>

  {% if object_perms.has_change_perm or object_perms.has_delete_perm %}
    <div
      class="container-fluid bg-secondary py-2 d-flex justify-content-center">
      {% if object_perms.has_change_perm %}
        <a
          href="{% url 'entries:edit' pk=entryset.pk %}"
          class="btn btn-info font-weight-bold mr-2"
        >
          {% trans "Edit" %}
        </a>
      {% endif %}

      {% if object_perms.has_delete_perm %}
        <a
          href="{% url 'entries:delete' pk=entryset.pk %}"
          class="btn btn-danger font-weight-bold"
        >
          {% trans "Delete" %}
        </a>
      {% endif %}
    </div>
  {% endif %}

  {{ block.super }}

  <div class="row row-cols-1">
    {% for entry in entryset.entries.all %}
      <div
        class="col p-4 {% if not forloop.counter0|divisibleby:"2" %}bg-light{% endif %}"
      >
        <div class="row row-cols-1">
          <div class="col d-flex justify-content-center">
            <h4 class="my-0 mr-2">
              <span class="badge badge-dark">
                {{ entry.get_type_display }}
              </span>
            </h4>

            {% if entry.origin.pk != entryset.pk %}
              <h4 class="mr-2">
                <a
                  href="{{ entry.origin.get_absolute_url }}"
                  class="badge badge-primary"
                >
                  {% trans "Origin" %}
                </a>
              </h4>
            {% endif %}

            <h4>
              <span class="badge badge-info">
                🔗 {{ entry.num_of_sets }}
              </span>
            </h4>
          </div>

          <div class="col my-2 d-flex justify-content-center">
            {% if entry.type == 0 %}
              <div class="jumbotron py-4 mx-4 mb-0 position-relative text-center">
                <div class="container">
                  {% if entry.label %}
                    <h3 class="font-weight-light">
                      {{ entry.label }}
                    </h3>
                  {% endif %}

                  <a
                    href="{{ entry.url }}"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="btn btn-link btn-lg text-monospace stretched-link"
                  >
                    {{ entry.url }}
                  </a>

                </div>
              </div>
            {% else %}
              {{ entry.render }}
            {% endif %}
          </div>

          {% if user.is_authenticated %}
            <div class="col d-flex justify-content-center">
              <form action="{% url 'entries:repost' pk=entry.pk %}" method="post" novalidate>
                {% csrf_token %}
                <button type="submit" class="btn btn-primary font-weight-bold">
                  {% trans "Repost" %}
                </button>
              </form>
            </div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="jumbotron jumbotron-fluid mb-0 py-4 bg-dark text-light">
    <div class="container">
      <h4 class="display-4 text-center mb-3">
        {% trans "Replies" %}
      </h4>

      {% if entryset.num_replies %}
        {% load static mptt_tags %}

        {% recursetree entryset.replies.all %}
          <div id="reply-{{ node.pk }}" class="media my-3">
            <img
              src="{% static 'img/user_light.svg' %}"
              width="56"
              height="56"
              alt="user image"
              class="rounded mr-2 align-self-start"
            >

            <div class="media-body">
              <div class="d-flex align-items-center">
                {% with node.get_author as author %}
                  {% if author.is_authenticated %}
                    <a
                      href="{{ author.get_absolute_url }}"
                      class="text-decoration-none mr-2"
                    >
                      {{ author.username }}
                    </a>
                  {% else %}
                    <span class="mr-2">
                      {{ author.username }}
                    </span>
                  {% endif %}
                {% endwith %}

                <small>
                  {{ node.created|date:"SHORT_DATETIME_FORMAT" }}
                </small>
              </div>

              <p class="font-weight-bold my-1">{{ node.text }}</p>

              <div class="d-flex">
                <a
                  href="{% url 'replies:post' %}?entryset={{ entryset.pk }}&reply={{ node.pk }}"
                  class="text-decoration-none"
                >
                  {% trans "Reply" %}
                </a>
              </div>

              {{ children }}
            </div>
          </div>
        {% endrecursetree %}
      {% else %}
        <p class="lead text-center">
          {% trans "No replies yet. Be the first to add one." %}
        </p>
      {% endif %}

      <div class="d-flex justify-content-center">
        <a
          href="{% url 'replies:post' %}?entryset={{ entryset.pk }}"
          class="btn btn-outline-primary btn-lg px-4 font-weight-bold"
        >
          {% trans "Reply" %}
        </a>
      </div>
    </div>
  </div>
{% endblock content %}

linkysets/templates/entries/entryset_form.html
{% extends 'hero.html' %}
{% load i18n static %}

{% block hero_content %}
  {{ block.super }}

  <form
    action="{{ request.path_info }}"
    method="post"
    novalidate
    autocomplete="off"
    id="entryset-form"
  >
    {% csrf_token %}

    {% if formset.non_form_errors %}
      <div class="non-form-errors">
        {% for error in formset.non_form_errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
        {% endfor %}
      </div>
    {% endif %}

    <div class="form-group">
      <label for="{{ form.name.id_for_label }}">
        {{ form.name.label }}
      </label>

      <input
        type="text"
        name="{{ form.name.html_name }}"
        value="{{ form.name.value|default_if_none:"" }}"
        id="{{ form.name.id_for_label }}"
        {% if field.field.required %}required{% endif %}
        class="form-control"
      >

      <small class="form-text text-muted">
        {{ form.name.help_text }}
      </small>
    </div>

    <hr>

    {{ formset.management_form }}
    {% for form in formset.forms %}
      {% include "entries/includes/entry_form.html" with form=form %}
    {% endfor %}

    <div class="mb-2">
      <button type="button" id="add-entry" class="btn btn-dark btn-sm px-2">
        {% trans "Add" %}
      </button>
    </div>

    <div>
      <button type="submit" class="btn btn-primary btn-lg px-4">
        {{ submit_text }}
      </button>
    </div>
  </form>

  <div id="empty-form" class="d-none">
    {% include "entries/includes/entry_form.html" with form=formset.empty_form %}
  </div>
{% endblock hero_content %}

{% block js %}
  {{ block.super }}
  <script src="{% static 'js/entryset_form.js' %}"></script>
{% endblock js %}

linkysets/templates/entries/home.html
{% extends 'base.html' %}
{% load i18n humanize common_tags %}

{% block content %}
  <div class="jumbotron jumbotron-fluid py-4 bg-dark text-light">
    <div class="container">
      <h4 class="h1 font-weight-bold">
        Linkysets
      </h4>

      <p class="lead">
        {% trans "Create your fascinating content sets 🥳" %}
      </p>

      <a
        href="{% url 'entries:create' %}"
        class="btn btn-success btn-lg font-weight-bold px-4"
      >
        {% trans "Create" %}
      </a>
    </div>
  </div>

  {{ block.super }}

  <div class="container">
    <div class="row row-cols-1">
      <div class="col px-0">
        <h4 class="display-4 text-center">
          {% trans "Check out our users sets" %}
        </h4>
      </div>

      <div class="col px-0">
        <ul class="list-unstyled">
          {% for entryset in page_obj %}
            {% include "entries/includes/entryset_item.html" with entryset=entryset %}
          {% endfor %}
        </ul>
      </div>

      <div class="col px-0 d-flex justify-content-center">
        {% include "pagination.html" with page_obj=page_obj %}
      </div>
    </div>
  </div>
{% endblock content %}